name 'chef-teamcity'
maintainer 'Alex Falkowski'
maintainer_email 'alexrfalkowski@gmail.com'
license 'All rights reserved'
description 'Installs/Configures TeamCity agent/server.'
long_description 'Installs/Configures TeamCity agent/server.'
version '0.1.0'
